In [1]:
import numpy as np
from scipy.linalg import svd

In [42]:
X = np.random.normal(0, 1, (10, 2))

In [43]:
u1, s1, vt1 = svd(X, full_matrices=False)

In [85]:
Z = np.hstack([u1] * 2)
Z = Z @ np.diag([2, 1, 1, 2])

In [86]:
u2, s2, vt2 = svd(Z, full_matrices=False)

In [87]:
np.corrcoef(u1, u2[:, :2], rowvar=False)[:2, 2:]

array([[ 1.        , -0.00139413],
       [ 0.00139413, -1.        ]])

In [31]:
u1

array([[-0.36228834,  0.33770927, -0.05113998],
       [ 0.34966977,  0.83879778,  0.36651057],
       [-0.31367977,  0.41599302, -0.78126742],
       [-0.64021035, -0.00999825,  0.31061931],
       [-0.48807163,  0.09602377,  0.39521079]])

In [32]:
u2

array([[ 0.33770927, -0.36228834,  0.10549024,  0.77981423],
       [ 0.83879778,  0.34966977, -0.06655109, -0.31635175],
       [ 0.41599302, -0.31367977,  0.25652784,  0.02348563],
       [-0.00999825, -0.64021035,  0.43093449, -0.52245818],
       [ 0.09602377, -0.48807163, -0.8561143 , -0.1352672 ]])

In [37]:
vt2

array([[-1.12974202e-16,  7.07106781e-01,  1.11022302e-16,
         7.07106781e-01],
       [ 7.07106781e-01,  0.00000000e+00,  7.07106781e-01,
         0.00000000e+00],
       [-1.52624051e-01,  6.90438918e-01,  1.52624051e-01,
        -6.90438918e-01],
       [-6.90438918e-01, -1.52624051e-01,  6.90438918e-01,
         1.52624051e-01]])